### ISSUE TITLE
Quick Check Todo

### ISSUE THREAD

**Issue by Coo3n** [Coo3n/Quick-Cheque#1]
1) АВТОРИЗАЦИЯ / РЕГИСТРАЦИЯ

- [x] Сверстать меню авторизации 
- [x] Сверстать меню регистрации по почте
- [ ] Прикрутить возможность авторизации через Google
- [ ] Прикрутить возможность авторизации через VK
- [ ] Прикрутить возможность авторизации через Почту
- [x] Сделать проверку зарегистрирован ли пользователь
- [x] Сделать проверку на корректность ввода логина и пароля

**Comment by Coo3n** [comment]
- [ ] ПРИВЕТ

**Comment by Coo3n** [comment]
2) ИНИЦИАЛИЗАЦИЯ ПРОДУКТОВ

- [ ] Сверстать меню доп. меню перед инициализацией списка (Редактирование, повтор фото) 
- [x] Сверстать меню для списка продуктов
- [ ] Реализовать функции фотографирования чека
- [x] Реализовать функцию ручного добавление чека
- [ ] Реализовать функцию редактирование некорректного текста продукта
- [ ] Реализовать функцию для повторного фотографирования чека
- [ ] Реализовать функцию удаление продукта
- [ ] Реализовать функцию для удаления всего чека

**Comment by Coo3n** [comment]
3) РАСПРЕДЕЛЕНИЕ ПРОДУКТОВ ПОЛЬЗОВАТЕЛЯМ

- [ ] Сделать функцию проверки полноты распределения чека (0/100%)
- [ ] Сделать отображение людей, которые вписались в продукт (иконки)

Для админа:
- [ ] Сделать функцию для добавления людей к какому-то продукту
- [ ] Сделать функцию закрытия чека
- [ ] Сделать функцию для выбора количества купленного продукта пользователем

Для пользователя:
- [ ] Сделать функцию для выбора количества купленного продукта пользователем
- [ ] Сделать функцию выбора продукта для оплаты

**Comment by Coo3n** [comment]
4) ОПЛАТА ЧЕКА

- [ ] Прикрутить оплату по СБП
- [ ] Прикрутить оплату по QIWI
- [ ] Прикрутить оплату  по юMoney
- [ ] Прикрутить безналичную оплату с подтверждением админа
- [ ] Функция для выдачи ссылки на оплату чека
- [ ] Функция на проверку, что оплата прошла

**Comment by PopovIV** [comment]
5. Главное меню 

- [x] Создание к мероприятию 
- [x] Присоединение к мероприятию (по QR-коду, по id)
- [x] Поиск мероприятий
